#!/usr/bin/env python
import os
import sys

cwd = os.getcwd()
orig_prog_name = os.path.basename(cwd)
build_dir = os.path.join(cwd, "build")

try:
    os.mkdir(build_dir)
except:
     print 'build dir exists'

version = raw_input("version: ")
clean = raw_input("clean build dir: (y/n):")
if clean == 'y':
    os.system("rm -R %s/*" % build_dir)
program_name = orig_prog_name + "-" + version
src_dir = os.path.join(build_dir, program_name) 

try:
    os.mkdir(src_dir)
except:
    sys.exit("%s already exists, exiting." % src_dir)
unwanted_files = ['*.kpf', '*.pyc', '.gitignore']
wanted_dirs = ['glade']
wanted = raw_input("add wanted dirs (glade is already included)")
if wanted is not "":
    wanted = wanted.split(" ")
    for w in wanted:
        wanted_dirs.append(w)
print 'Wanted dirs:', wanted_dirs

os.system("cp %s/* %s" % (cwd, src_dir))

for dir in wanted_dirs:
    os.system("cp -R %s %s" % (dir, src_dir))

for file in unwanted_files:
    os.system("rm %s" % src_dir + os.sep + file)
os.chdir(build_dir)
os.system("tar -zvcf %s.tar.gz %s" % (program_name, program_name))
os.system("cp %s.tar.gz %s.orig.tar.gz" % (program_name, orig_prog_name + "_" +
version))
#check build directory first to see if we have the debian base
#if not import a generic one
if os.path.exists(cwd + "/.debian-base"):
    os.system("cp -r %s %s" % (cwd + "/.debian-base", src_dir + "/debian"))
else:
    os.system("cp -r %s %s" % ("/home/wode/programming/debian-base", src_dir + "/debian"))
    os.system("cp -r %s %s" % ("/home/wode/programming/debian-base", cwd +
    "/.debian-base"))


bin = raw_input("Change version in binary file. The version variable must be in the form __version__ leave blank to use %s as your binary file" % orig_prog_name)
if bin == "":
    bin = orig_prog_name
lines = open(src_dir + "/" + bin, "r").readlines()
for i in range(0, len(lines)):
    if "__version__" in lines[i]:
        old_version = lines[i].split('"')
        lines[i] = old_version[0] + '"' + version + '"' + "\n"
        break

f = open (src_dir + "/" + bin, "w")
for line in lines:
    f.write(line)
f.close()


f = open(src_dir + "/debian/changelog", "w")
f.write("%s (%s-1) intrepid; urgency=low" % (orig_prog_name, version))
f.close()

os.chdir(cwd)
os.system("git log")
os.chdir(src_dir)
os.system("vim debian/changelog")


