#!/usr/bin/env python
import optparse
import os
import shutil


def convert_file(filepath, from_enc, to_enc):
    filepath = os.path.abspath(filepath)
    dir = os.path.dirname(filepath)
    temp_file = os.path.join(dir, 'temp-subdemanglerFile')
    try:
        shutil.move(filepath, os.path.join(dir, temp_file))
    except IOError:
        sys.exit('The specified file %s could not be found.' % filepath)
    garbage = file(temp_file).read()
    garbage = garbage.decode(from_enc)
    clean = garbage.encode(to_enc)
    file(filepath, 'w').write(clean)
    os.remove(temp_file)
    
    
def run():
    parser = optparse.OptionParser()
    parser.add_option('--from_encoding', '-f', default='windows-1251')
    parser.add_option('--to_encoding', '-t', default='utf-8')
    options, args = parser.parse_args()
    print options
    if len(args) is not 1:
        parser.error("You must specify a filename to convert")
    convert_file(args[0], options.from_encoding, options.to_encoding)
    
if __name__ == '__main__':
    run()
    